Now you can indicate wakeup application status on search tab too
jeamxn/dipull pull request #226
Opened 2024-06-22 12:41 UTC by yeonfish6040

검색창에서도 자신이 신청한 기상곡이 리스트에 있을 경우, 해당 리스트 항목의 체크마크를 초록색으로 바뀌도록 변경하였습니다.

2024-06-23 02:47 UTC, jeamxn requested changes
수정해주면 Merge 할게용

2024-06-23 02:47 UTC, jeamxn commented on src/app/(login)/wakeup/search/page.tsx
> +      const songList = (await getWakeup(userInfo.id, userInfo.gender)).my;
```ts
const userInfo = await getUserInfo();
const songList = (await getWakeup(userInfo.id, userInfo.gender)).my;
```
이건 서버측 함수들이라 클라이언트 측에서 사용하지 말아주세용
-> 토큰 갱신 안 되어서,,,

2024-06-23 02:47 UTC, jeamxn commented on src/app/(login)/wakeup/search/page.tsx
> +      }));
클라이언트에서 처리하지 말고 백엔드에서 처리하고 보내주는게 좋을 듯

2024-06-23 02:47 UTC, jeamxn commented on src/app/(login)/wakeup/search/page.tsx
> +import {getUserInfo} from "@/utils/server";
ESLint 키고 작업 부탁드릴게요. README 설정대로 해주세여..

2024-06-23 05:00 UTC, yeonfish6040 commented on src/app/(login)/wakeup/search/page.tsx
> +import {getUserInfo} from "@/utils/server";
어라라...? 키고 했는데요...ㅠㅠ

2024-06-23 05:00 UTC, jeamxn commented on src/app/(login)/wakeup/search/page.tsx
> +import {CustomYoutubeSearchResult} from "@/app/api/wakeup/utils";
eslint 안 켜져있는 것 같은데..

2024-06-23 05:04 UTC, jeamxn requested changes
eslint 켜고 다시 저장 부탁드릴게여

2024-06-23 11:23 UTC, jeamxn requested changes
수정해주세용

2024-06-23 11:23 UTC, jeamxn commented on src/app/(login)/wakeup/search/page.tsx
> +      const res_search = await instance.post(
근뎅 이런 방식으로 하면 검색 했을 때만 초록색으로 바뀌니깐 따로 Array 만들어놔서 put이 성공적으로 되고, 검색 결과들이 array안에 있다면 초록으로 바꾸는 방식이 더 좋을 듯합니다!

2024-06-23 11:24 UTC, jeamxn requested changes

2024-06-23 11:24 UTC, jeamxn commented on .eslintrc.json
> +    "object-curly-spacing": ["error", "always"],
> 이거 직접 수정하지 말아주세여

2024-06-24 03:07 UTC, jeamxn requested changes
1. 원 커밋에서 eslint 건들이지 말기
2. console.log 삭제

1, 2번 수정 부탁드려여

2024-06-24 03:07 UTC, jeamxn commented on src/app/(login)/wakeup/search/page.tsx
> +      console.log(list);
console.log 삭제 부탁드려여

2024-06-24 03:12 UTC, yeonfish6040 commented
수정 완료했습니다

2024-06-24 03:14 UTC, jeamxn requested changes
코드 이쁘게 히ㅣ히

2024-06-24 03:14 UTC, jeamxn commented on src/app/(login)/wakeup/search/page.tsx
> +      setList(list.map(e => { e.my = e.id === select.id; return e; }));
```ts
setList(list.map(e => ({
  ...e,
  my: e.id === select.id,
})));
```
이런 형식으로 수정 가능?? post.ts도 같이 부탁!!

2024-06-24 03:15 UTC, yeonfish6040 commented on src/app/(login)/wakeup/search/page.tsx
> +      setList(list.map(e => { e.my = e.id === select.id; return e; }));
넵...ㅋㅋ!

2024-06-24 03:20 UTC, yeonfish6040 commented
히히... 코드가 아주 이쁘네요....♥

2024-06-24 03:22 UTC, jeamxn requested changes
근데 이거 버그 있어
검색 창에서 서로 다른 곡 추가하면 하나만 초록색으로 떠

2024-06-24 03:26 UTC, yeonfish6040 commented
네 그거...

2024-06-24 03:28 UTC, yeonfish6040 commented
수정했습니다

2024-06-24 03:31 UTC, jeamxn approved these changes
좋아유

2024-06-24 03:35 UTC, merged

2024-06-24 03:35 UTC, jeamxn commented
Dev 브랜치에 merge 후 빌드 제대로 되는지 확인하고 main에 넣겠습니당