feat: add selected wakeup indicator
jeamxn/dipull pull request #293
Opened 2024-07-01 01:00 UTC by yeonfish6040

- 당일 선택된 기상곡을 확인 가능하게 만들었습니다.
- ! states의 업데이트가 필요합니다
states.ts에 명시되어있습니다.

2024-07-01 02:54 UTC, jeamxn requested changes
수정 부탁드리요

2024-07-01 02:54 UTC, jeamxn commented on src/app/cron/timetable/get.ts
> +          if (time.changed && day === today_day) {
main 브랜치하고 fetch 해주실 수 있나여

2024-07-01 02:54 UTC, jeamxn commented on src/app/(login)/wakeup/utils.ts
> +  const day_selected = new Date(`${selected.date.substring(4,6)}/${selected.date.substring(6,8)}/${selected.date.substring(0,4)}`);
이거 연산 moment 사용해주십셔

2024-07-01 02:54 UTC, jeamxn commented on src/app/(login)/teacher/wakeup/TeacherWakeupContent.tsx
> +    setDateDiff(calcDateDiff(selected));
첫 번째 init은 위에서 바로 보이게
지금처럼 이렇게 되면 한 번 끊겼다가 보임

2024-07-01 02:54 UTC, jeamxn commented on src/app/(login)/wakeup/list/ListContent.tsx
> +                colSpan={2}>{gender === "male" ? "남" : "여"}학생 {calcDateDiff(selected)}의 기상송
```
TypeError: undefined is not an object (evaluating 'selected.date')
```

선택 안 되어있으면 이런 오류 뜨네여

2024-07-01 02:54 UTC, jeamxn commented on src/app/api/wakeup/selected/get.ts
> +  const data = await statesCollection.findOne({
getStates 사용 부탁

2024-07-01 02:54 UTC, jeamxn commented on src/app/(login)/teacher/wakeup/TeacherWakeupContent.tsx
> +import { calcDateDiff } from "@/app/(login)/wakeup/utils";
선생님 페이지에서도
```
TypeError: undefined is not an object (evaluating 'selected.date')
```
오류 뜨네요...

2024-07-01 02:54 UTC, jeamxn commented on src/app/(login)/wakeup/utils.ts
> +  const day_selected = new Date(`${selected.date.substring(4,6)}/${selected.date.substring(6,8)}/${selected.date.substring(0,4)}`);
그리고 Date 형식은 2006-09-27 이렇게 해주면 감사합니다

2024-07-01 02:54 UTC, jeamxn commented on src/app/api/teacher/wakeup/put.ts
> +  const res = await axios.get(url, {
이거 오류 핸들링 해야됨

2024-07-01 07:24 UTC, yeonfish6040 commented
> 수정 부탁드리요

수정 완료했습니당

2024-07-02 10:16 UTC, jeamxn requested changes
수정 ㅎㅎ부탁 ㅎㅎ

2024-07-02 10:28 UTC, yeonfish6040 commented
ㅠㅠ...

2024-07-02 10:31 UTC, yeonfish6040 commented
> 수정 ㅎㅎ부탁 ㅎㅎ

States 다시 확인 부탁드립니다. States 지우니까 같은 오류가 나고 다시 만드니까 해결되네요..!

2024-07-02 10:47 UTC, yeonfish6040 commented
일단 검사단에 한단계 더 추가해놓았습니다.

2024-07-03 05:22 UTC, yeonfish6040 commented
선배님의 관심이가 필요해여...
선배님은 나한테 관심이를 주지 않아..

2024-07-03 23:23 UTC, jeamxn requested changes
Error: Cannot convert undefined or null to object

src/app/api/wakeup/server.ts (73:38) @ call

해결..해..보아.
어딘가 구조적으로 잘못된 듯

2024-07-03 23:23 UTC, jeamxn commented on src/app/api/wakeup/server.ts
> +  if (Object.prototype.hasOwnProperty.call(data, "date") || data.date === undefined || data.date === "") return { id: null };
여기서 오류난대요 ㅜㅠ

2024-07-03 23:34 UTC, yeonfish6040 commented
https://github.com/jeamxn/dipull/assets/72007187/71783a72-99d1-40a9-9b48-4710fd3af168

States를 다른 DB에 넣으신건 아니신지...
이것이 문제가 아니라면 gender가 male이나 female이 아닌건데..

2024-07-03 23:40 UTC, yeonfish6040 commented
검사단에 gender가 이상할경우도 거르게 해놨습니다... 절대 오류는 안날건데요...
습.. 저렇게 나오면 선배님 계정에서 제대로 동작하지 않을텐데... 고민이네요...

2024-07-11 10:34 UTC, jeamxn approved these changes

2024-07-11 10:37 UTC, merged